ALTER TABLE `invoices` MODIFY COLUMN `status` enum('generada','enviada','cobrada','anulada','abonada') NOT NULL DEFAULT 'generada';--> statement-breakpoint
ALTER TABLE `quotes` MODIFY COLUMN `status` enum('borrador','enviado','visualizado','aceptado','convertido_carrito','pagado','convertido_reserva','facturado','rechazado','expirado','perdido') NOT NULL DEFAULT 'borrador';--> statement-breakpoint
ALTER TABLE `invoices` ADD `invoiceType` enum('factura','abono') DEFAULT 'factura' NOT NULL;--> statement-breakpoint
ALTER TABLE `invoices` ADD `paymentMethod` enum('redsys','transferencia','efectivo','otro') DEFAULT 'redsys';--> statement-breakpoint
ALTER TABLE `invoices` ADD `paymentValidatedBy` int;--> statement-breakpoint
ALTER TABLE `invoices` ADD `paymentValidatedAt` timestamp;--> statement-breakpoint
ALTER TABLE `invoices` ADD `transferProofUrl` text;--> statement-breakpoint
ALTER TABLE `invoices` ADD `transferProofKey` text;--> statement-breakpoint
ALTER TABLE `invoices` ADD `isAutomatic` boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE `invoices` ADD `creditNoteForId` int;--> statement-breakpoint
ALTER TABLE `invoices` ADD `creditNoteReason` text;--> statement-breakpoint
ALTER TABLE `invoices` ADD `sentAt` timestamp;--> statement-breakpoint
ALTER TABLE `invoices` ADD `lastSentAt` timestamp;--> statement-breakpoint
ALTER TABLE `invoices` ADD `sentCount` int DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `leads` ADD `activitiesJson` json;--> statement-breakpoint
ALTER TABLE `quotes` ADD `acceptedAt` timestamp;--> statement-breakpoint
ALTER TABLE `quotes` ADD `transfer_proof_url` text;--> statement-breakpoint
ALTER TABLE `quotes` ADD `transfer_proof_key` text;--> statement-breakpoint
ALTER TABLE `quotes` ADD `transfer_confirmed_at` timestamp;--> statement-breakpoint
ALTER TABLE `quotes` ADD `transfer_confirmed_by` varchar(255);--> statement-breakpoint
ALTER TABLE `quotes` ADD `payment_method` enum('redsys','transferencia','efectivo','otro');--> statement-breakpoint
ALTER TABLE `quotes` ADD `isAutoGenerated` boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE `quotes` ADD `reminderCount` int DEFAULT 0;--> statement-breakpoint
ALTER TABLE `quotes` ADD `lastReminderAt` timestamp;--> statement-breakpoint
ALTER TABLE `reservations` ADD `quote_id` int;--> statement-breakpoint
ALTER TABLE `reservations` ADD `quoteSource` varchar(32);--> statement-breakpoint
ALTER TABLE `reservations` ADD `invoiceId` int;--> statement-breakpoint
ALTER TABLE `reservations` ADD `invoiceNumber` varchar(32);--> statement-breakpoint
ALTER TABLE `reservations` ADD `paymentMethod` enum('redsys','transferencia','efectivo','otro');--> statement-breakpoint
ALTER TABLE `reservations` ADD `paymentValidatedBy` int;--> statement-breakpoint
ALTER TABLE `reservations` ADD `paymentValidatedAt` bigint;--> statement-breakpoint
ALTER TABLE `reservations` ADD `transferProofUrl` text;--> statement-breakpoint
ALTER TABLE `reservations` ADD `channel` enum('web','crm','telefono','email','otro') DEFAULT 'web';