CREATE TABLE `reav_costs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`expedientId` int NOT NULL,
	`description` varchar(256) NOT NULL,
	`providerName` varchar(256),
	`providerNif` varchar(64),
	`invoiceRef` varchar(128),
	`invoiceDate` varchar(10),
	`amount` decimal(10,2) NOT NULL,
	`currency` varchar(8) NOT NULL DEFAULT 'EUR',
	`category` enum('transporte','alojamiento','actividad','restauracion','guia','seguro','otros') NOT NULL DEFAULT 'otros',
	`isPaid` boolean NOT NULL DEFAULT false,
	`paidAt` timestamp,
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `reav_costs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `reav_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`expedientId` int NOT NULL,
	`side` enum('client','provider') NOT NULL,
	`docType` enum('factura_emitida','factura_recibida','contrato','voucher','confirmacion_proveedor','otro') NOT NULL DEFAULT 'otro',
	`title` varchar(256) NOT NULL,
	`fileUrl` text,
	`fileKey` text,
	`mimeType` varchar(128),
	`fileSize` int,
	`notes` text,
	`uploadedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `reav_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `reav_expedients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`expedientNumber` varchar(32) NOT NULL,
	`invoiceId` int,
	`reservationId` int,
	`clientId` int,
	`agentId` int,
	`serviceDescription` text,
	`serviceDate` varchar(10),
	`serviceEndDate` varchar(10),
	`destination` varchar(256),
	`numberOfPax` int DEFAULT 1,
	`saleAmountTotal` decimal(10,2) DEFAULT '0',
	`providerCostEstimated` decimal(10,2) DEFAULT '0',
	`providerCostReal` decimal(10,2) DEFAULT '0',
	`agencyMarginEstimated` decimal(10,2) DEFAULT '0',
	`agencyMarginReal` decimal(10,2) DEFAULT '0',
	`reavTaxBase` decimal(10,2) DEFAULT '0',
	`reavTaxAmount` decimal(10,2) DEFAULT '0',
	`fiscalStatus` enum('pendiente_documentacion','documentacion_completa','en_revision','cerrado','anulado') NOT NULL DEFAULT 'pendiente_documentacion',
	`operativeStatus` enum('abierto','en_proceso','cerrado','anulado') NOT NULL DEFAULT 'abierto',
	`internalNotes` text,
	`closedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `reav_expedients_id` PRIMARY KEY(`id`),
	CONSTRAINT `reav_expedients_expedientNumber_unique` UNIQUE(`expedientNumber`)
);
