CREATE TABLE `coupon_redemptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`provider` varchar(64) NOT NULL DEFAULT 'Groupon',
	`productTicketingId` int,
	`productRealId` int,
	`customerName` varchar(256) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(32),
	`couponCode` varchar(128) NOT NULL,
	`securityCode` varchar(128),
	`attachmentUrl` text,
	`requestedDate` varchar(20),
	`station` varchar(128),
	`participants` int DEFAULT 1,
	`children` int DEFAULT 0,
	`comments` text,
	`statusOperational` enum('recibido','validado','reserva_generada','disfrutado','incidencia','cancelado') NOT NULL DEFAULT 'recibido',
	`statusFinancial` enum('pendiente_canje_proveedor','canjeado_en_proveedor','pendiente_cobro','cobrado','discrepancia') NOT NULL DEFAULT 'pendiente_canje_proveedor',
	`ocrConfidenceScore` int,
	`ocrStatus` enum('alta','media','baja','conflicto'),
	`ocrRawData` json,
	`duplicateFlag` boolean NOT NULL DEFAULT false,
	`duplicateNotes` text,
	`realAmount` decimal(10,2),
	`settlementJustificantUrl` text,
	`settledAt` timestamp,
	`reservationId` int,
	`adminUserId` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `coupon_redemptions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ticketing_products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(256) NOT NULL,
	`provider` varchar(64) NOT NULL DEFAULT 'Groupon',
	`linkedProductId` int,
	`stationsAllowed` json,
	`rules` text,
	`commission` decimal(5,2) DEFAULT '20.00',
	`expectedPrice` decimal(10,2),
	`active` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ticketing_products_id` PRIMARY KEY(`id`)
);
