CREATE TABLE `feature_flags` (
  `id` int AUTO_INCREMENT NOT NULL,
  `key` varchar(128) NOT NULL,
  `name` varchar(256) NOT NULL,
  `description` text,
  `module` varchar(64) NOT NULL DEFAULT 'general',
  `enabled` boolean NOT NULL DEFAULT true,
  `default_enabled` boolean NOT NULL DEFAULT true,
  `risk_level` enum('low','medium','high') NOT NULL DEFAULT 'low',
  `created_at` timestamp NOT NULL DEFAULT (now()),
  `updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `feature_flags_id` PRIMARY KEY(`id`),
  CONSTRAINT `feature_flags_key_unique` UNIQUE(`key`)
);
--> statement-breakpoint
CREATE TABLE `system_settings` (
  `id` int AUTO_INCREMENT NOT NULL,
  `key` varchar(128) NOT NULL,
  `value` text,
  `value_type` enum('string','number','boolean','json') NOT NULL DEFAULT 'string',
  `category` varchar(64) NOT NULL DEFAULT 'general',
  `label` varchar(256) NOT NULL,
  `description` text,
  `is_sensitive` boolean NOT NULL DEFAULT false,
  `is_public` boolean NOT NULL DEFAULT false,
  `created_at` timestamp NOT NULL DEFAULT (now()),
  `updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `system_settings_id` PRIMARY KEY(`id`),
  CONSTRAINT `system_settings_key_unique` UNIQUE(`key`)
);
--> statement-breakpoint
INSERT IGNORE INTO `feature_flags` (`key`, `name`, `description`, `module`, `enabled`, `default_enabled`, `risk_level`) VALUES
  ('tpv_enabled', 'Módulo TPV', 'Habilita el módulo de Punto de Venta presencial', 'tpv', true, true, 'medium'),
  ('tpv_email_notifications_enabled', 'Notificaciones email TPV', 'Envía email al abrir y cerrar sesión de caja', 'tpv', true, true, 'low'),
  ('tpv_auto_reconciliation_enabled', 'Conciliación automática TPV', 'Concilia automáticamente movimientos al cerrar sesión', 'tpv', false, false, 'high'),
  ('tpv_cash_closure_enabled', 'Cierre de caja automático', 'Crea fin_cash_closures al cerrar sesión TPV', 'tpv', true, true, 'medium'),
  ('bank_movements_module_enabled', 'Módulo movimientos bancarios', 'Habilita la importación y gestión de extractos bancarios', 'bank', true, true, 'medium'),
  ('bank_auto_expense_suggestions_enabled', 'Sugerencias automáticas de gastos', 'Propone gastos automáticamente al detectar movimientos bancarios', 'bank', false, false, 'high'),
  ('card_terminal_batches_enabled', 'Módulo batches de datáfono', 'Habilita la gestión de liquidaciones de datáfono', 'card_terminal', true, true, 'medium'),
  ('card_terminal_auto_match_enabled', 'Conciliación automática datáfono', 'Concilia automáticamente batches de datáfono con movimientos bancarios', 'card_terminal', true, true, 'medium'),
  ('email_ingestion_enabled', 'Ingesta de emails', 'Habilita la lectura de emails IMAP para importación de operaciones', 'email_ingestion', true, true, 'medium'),
  ('cash_register_module_enabled', 'Módulo caja registradora', 'Habilita el panel de caja y seguimiento de fondos', 'cash_register', true, true, 'medium'),
  ('crm_module_enabled', 'Módulo CRM', 'Habilita leads, presupuestos y gestión de clientes', 'crm', true, true, 'medium'),
  ('crm_auto_send_budget_enabled', 'Envío automático de presupuestos', 'Envía presupuestos automáticamente al crearlos desde el CRM', 'crm', false, false, 'medium'),
  ('ticketing_module_enabled', 'Módulo ticketing', 'Habilita la venta y gestión de entradas individuales', 'ticketing', true, true, 'medium'),
  ('cancellations_module_enabled', 'Módulo cancelaciones', 'Habilita el seguimiento y procesamiento de cancelaciones', 'cancellations', true, true, 'medium'),
  ('cancellation_stale_job_enabled', 'Cron cancelaciones pendientes', 'Ejecuta el job periódico que detecta reservas con pago pendiente vencido', 'cancellations', true, true, 'medium'),
  ('expense_auto_creation_from_bank_enabled', 'Creación automática de gastos desde banco', 'Crea gastos automáticamente al detectar cargos bancarios de proveedores', 'expenses', false, false, 'high'),
  ('reav_module_enabled', 'Módulo expedientes REAV', 'Habilita la gestión de expedientes bajo régimen especial de agencias de viaje', 'reav', true, true, 'medium'),
  ('suppliers_module_enabled', 'Módulo proveedores y liquidaciones', 'Habilita la gestión de proveedores y liquidaciones', 'suppliers', true, true, 'medium'),
  ('hotel_module_enabled', 'Módulo hotel', 'Habilita la gestión de habitaciones y reservas de hotel', 'hotel', true, true, 'medium'),
  ('spa_module_enabled', 'Módulo spa', 'Habilita la gestión de reservas de spa', 'spa', true, true, 'medium'),
  ('restaurants_module_enabled', 'Módulo restaurantes', 'Habilita la gestión de reservas de restaurante', 'restaurants', true, true, 'medium'),
  ('quote_reminder_job_enabled', 'Cron recordatorio de presupuestos', 'Envía recordatorios automáticos a clientes con presupuestos próximos a vencer', 'crm', true, true, 'low');
--> statement-breakpoint
INSERT IGNORE INTO `system_settings` (`key`, `value`, `value_type`, `category`, `label`, `description`, `is_sensitive`, `is_public`) VALUES
  ('email_reservations', '', 'string', 'email', 'Email de reservas', 'Dirección de correo para notificaciones de reservas. Vacío = reservas@nayadeexperiences.es', false, false),
  ('email_admin_alerts', '', 'string', 'email', 'Email de alertas admin', 'Dirección de correo para alertas de administración. Vacío = administracion@nayadeexperiences.es', false, false),
  ('email_accounting', '', 'string', 'email', 'Email de contabilidad', 'Dirección de correo para notificaciones contables. Vacío = administracion@nayadeexperiences.es', false, false),
  ('email_cancellations', '', 'string', 'email', 'Email de cancelaciones', 'Dirección de correo para notificaciones de cancelaciones. Vacío = reservas@nayadeexperiences.es', false, false),
  ('email_tpv_ingestion', '', 'string', 'email', 'Email de ingesta TPV', 'Dirección de correo monitoreada para ingesta de emails del datáfono. Vacío = administracion@nayadeexperiences.es', false, false),
  ('email_noreply_sender', '', 'string', 'email', 'Email remitente noreply', 'Dirección de remitente para emails transaccionales. Vacío = noreply@nayadeexperiences.es', false, false),
  ('email_copy_recipient', '', 'string', 'email', 'Email copia de reservas', 'Dirección que recibe copia de todas las reservas. Vacío = reservas@nayadeexperiences.es', false, false),
  ('bank_match_tolerance', '0.01', 'number', 'finance', 'Tolerancia conciliación bancaria (€)', 'Diferencia máxima en euros para considerar dos importes como iguales en conciliación bancaria', false, false),
  ('card_terminal_tolerance', '0.01', 'number', 'finance', 'Tolerancia datáfono (€)', 'Diferencia máxima en euros para conciliación de operaciones de datáfono', false, false),
  ('cash_register_tolerance', '0.01', 'number', 'finance', 'Tolerancia caja registradora (€)', 'Diferencia máxima en euros para considerar una caja cuadrada', false, false),
  ('cash_alert_threshold', '20.00', 'number', 'finance', 'Umbral alerta crítica de caja (€)', 'Diferencia de caja a partir de la cual la alerta se considera crítica (vs warning)', false, false),
  ('expense_bank_match_tolerance', '0.01', 'number', 'finance', 'Tolerancia gastos-banco (€)', 'Diferencia máxima para enlazar un gasto con un movimiento bancario', false, false),
  ('card_batch_tolerance', '0.01', 'number', 'finance', 'Tolerancia batch datáfono (€)', 'Diferencia máxima para conciliar un batch de datáfono', false, false),
  ('brand_name', 'Náyade Experiences', 'string', 'branding', 'Nombre de la empresa', 'Nombre completo de la empresa para emails y documentos', false, true),
  ('brand_short_name', 'Náyade', 'string', 'branding', 'Nombre corto', 'Nombre corto de la empresa', false, true),
  ('brand_domain', 'nayadeexperiences.es', 'string', 'branding', 'Dominio web', 'Dominio principal de la web', false, true),
  ('brand_address', '', 'string', 'branding', 'Dirección fiscal', 'Dirección fiscal completa', false, false),
  ('brand_phone', '', 'string', 'branding', 'Teléfono de contacto', 'Teléfono principal de contacto', false, true),
  ('brand_nif', '', 'string', 'branding', 'NIF/CIF', 'Número de identificación fiscal', false, false),
  ('brand_instagram', '', 'string', 'branding', 'Instagram', 'URL del perfil de Instagram', false, true),
  ('cancellation_stale_days', '3', 'number', 'operations', 'Días para reserva pendiente caducada', 'Número de días sin pago para considerar una reserva como pendiente caducada', false, false),
  ('quote_reminder_days_before', '7', 'number', 'operations', 'Días antes de vencimiento para recordatorio', 'Días de antelación para enviar recordatorio de presupuesto', false, false),
  ('quote_validity_days', '30', 'number', 'operations', 'Validez de presupuestos (días)', 'Número de días de validez por defecto para nuevos presupuestos', false, false),
  ('invoice_due_days', '30', 'number', 'operations', 'Plazo de pago facturas (días)', 'Días de vencimiento por defecto para facturas emitidas', false, false),
  ('imap_host', 'nayadeexperiences.es.correoseguro.dinaserver.com', 'string', 'imap', 'Servidor IMAP', 'Hostname del servidor IMAP para ingesta de emails', false, false),
  ('imap_user', 'administracion@nayadeexperiences.es', 'string', 'imap', 'Usuario IMAP', 'Dirección de email para autenticación IMAP', false, false),
  ('imap_port', '993', 'number', 'imap', 'Puerto IMAP', 'Puerto del servidor IMAP (993 con TLS, 143 sin TLS)', false, false),
  ('imap_tls', 'true', 'boolean', 'imap', 'IMAP con TLS', 'Usar conexión cifrada TLS para IMAP', false, false),
  ('redsys_environment', 'production', 'string', 'payments', 'Entorno Redsys', 'Entorno de Redsys: production o test', false, false),
  ('redsys_currency', '978', 'number', 'payments', 'Moneda Redsys (ISO 4217)', 'Código ISO 4217 de moneda: 978 = EUR', false, false),
  ('app_timezone', 'Europe/Madrid', 'string', 'app', 'Zona horaria', 'Zona horaria de la aplicación', false, false),
  ('app_locale', 'es-ES', 'string', 'app', 'Idioma/región', 'Locale de la aplicación para fechas y números', false, false),
  ('app_currency', 'EUR', 'string', 'app', 'Moneda', 'Moneda principal de la aplicación', false, false),
  ('tax_rate_general', '21', 'number', 'finance', 'IVA general (%)', 'Tipo de IVA general aplicable', false, false),
  ('tax_rate_reduced', '10', 'number', 'finance', 'IVA reducido (%)', 'Tipo de IVA reducido aplicable', false, false);
