/**
 * Seed/restore de experiencias Náyade
 * Uso: railway run node scripts/seed_experiences_runner.mjs
 */
import mysql from "mysql2/promise";

const CDN = "https://d2xsxph8kpxj0f.cloudfront.net/310519663410228097/AV298FS8t5SaTurBBRqhgQ/nayade/uploads";

const conn = await mysql.createConnection(process.env.DATABASE_URL);
console.log("✅ Conectado a MySQL");

// ── Helpers ─────────────────────────────────────────────────────────────────
async function upsertCategory(slug, name, sortOrder) {
  await conn.execute(
    `INSERT IGNORE INTO categories (slug, name, isActive, sortOrder) VALUES (?, ?, 1, ?)`,
    [slug, name, sortOrder]
  );
  const [rows] = await conn.execute(`SELECT id FROM categories WHERE slug = ?`, [slug]);
  return rows[0].id;
}

async function upsertLocation(slug, name, address) {
  await conn.execute(
    `INSERT IGNORE INTO locations (slug, name, address, isActive, sortOrder) VALUES (?, ?, ?, 1, 1)`,
    [slug, name, address]
  );
  const [rows] = await conn.execute(`SELECT id FROM locations WHERE slug = ?`, [slug]);
  return rows[0].id;
}

async function insertExp(data) {
  const cols = Object.keys(data).join(", ");
  const placeholders = Object.keys(data).map(() => "?").join(", ");
  await conn.execute(
    `INSERT IGNORE INTO experiences (${cols}) VALUES (${placeholders})`,
    Object.values(data)
  );
}

// ── 1. Categorías ────────────────────────────────────────────────────────────
const catAcuaticas  = await upsertCategory("actividades-acuaticas", "Actividades Acuáticas", 1);
const catDeportes   = await upsertCategory("deportes-acuaticos",    "Deportes Acuáticos",    2);
const catSpa        = await upsertCategory("spa-bienestar",         "SPA & Bienestar",        3);
const catPiscina    = await upsertCategory("piscina",               "Piscina & Baño",         4);
console.log("✅ Categorías:", { catAcuaticas, catDeportes, catSpa, catPiscina });

// ── 2. Ubicación ─────────────────────────────────────────────────────────────
const locId = await upsertLocation(
  "los-angeles-de-san-rafael",
  "Los Ángeles de San Rafael",
  "Club Náutico Los Ángeles de San Rafael, Segovia"
);
console.log("✅ Ubicación id:", locId);

// ── 3. Experiencias ──────────────────────────────────────────────────────────
const experiences = [
  {
    slug: "paseo-en-barco",
    title: "Paseo en Barco",
    shortDescription: "Navega por las tranquilas aguas del embalse de Los Ángeles de San Rafael rodeado de vegetación y vistas panorámicas.",
    description: "Una experiencia única surcando las apacibles aguas del embalse de Los Ángeles de San Rafael. A bordo disfrutarás de paisajes de ensueño, rodeado de vegetación frondosa y con las cumbres de la Sierra de Guadarrama como telón de fondo. Ideal para familias, parejas y grupos que buscan una actividad tranquila y memorable.",
    coverImageUrl: `${CDN}/1775049168929-vx1e7i.png`,
    image1: `${CDN}/1775049168929-vx1e7i.png`,
    image2: `${CDN}/1775049603095-8rkwvh.png`,
    image3: `${CDN}/1775049607679-rxudag.png`,
    image4: `${CDN}/1775049612665-6ts80x.png`,
    basePrice: "15.00",
    duration: "20 minutos",
    minPersons: 1,
    maxPersons: 50,
    difficulty: "facil",
    isFeatured: 0,
    isActive: 1,
    isPublished: 1,
    isPresentialSale: 1,
    categoryId: catAcuaticas,
    locationId: locId,
    includes: JSON.stringify(["Seguro de accidentes"]),
    excludes: JSON.stringify([]),
    fiscalRegime: "general_21",
    productType: "actividad",
    "pricing_type": "per_person",
    sortOrder: 1,
  },
  {
    slug: "entrada-general-piscina-club-nautico",
    title: "Entrada General Piscina Club Náutico",
    shortDescription: "Relájate y diviértete en nuestra piscina a orillas del embalse con amplias zonas de baño y solárium.",
    description: "Disfruta de la piscina del Club Náutico de Los Ángeles de San Rafael, situada a orillas del embalse con impresionantes vistas a la Sierra de Guadarrama. Cuenta con amplias zonas de solárium, acceso al lago y todas las comodidades para una jornada de descanso y recreo en familia o con amigos.",
    coverImageUrl: `${CDN}/1774281603494-er84vo.png`,
    image1: `${CDN}/1774281603494-er84vo.png`,
    image2: `${CDN}/1774281608106-4fqd45.png`,
    image3: `${CDN}/1774281619410-lefaql.png`,
    image4: null,
    basePrice: "7.00",
    duration: null,
    minPersons: 11,
    maxPersons: 100,
    difficulty: "facil",
    isFeatured: 0,
    isActive: 1,
    isPublished: 1,
    isPresentialSale: 1,
    categoryId: catPiscina,
    locationId: locId,
    includes: JSON.stringify(["Acceso a las instalaciones", "Seguro de accidentes"]),
    excludes: JSON.stringify(["Acceso a Bahía VIP"]),
    fiscalRegime: "general_21",
    productType: "actividad",
    "pricing_type": "per_person",
    sortOrder: 2,
  },
  {
    slug: "alquiler-dia-completo-tabla-de-wakeboard",
    title: "Alquiler Día Completo Tabla de Wakeboard",
    shortDescription: "Alquila tu tabla de wakeboard para todo el día y disfruta del embalse a tu ritmo combinando velocidad, equilibrio y emociones acuáticas.",
    description: "Vive la experiencia del wakeboard durante un día completo en el embalse de Los Ángeles de San Rafael. Ya seas principiante o experto, la tabla de wakeboard te permitirá deslizarte sobre el agua combinando velocidad, equilibrio y adrenalina en un entorno natural inigualable. Mínimo 2 personas.",
    coverImageUrl: `${CDN}/1775074493261-jccylv.jpg`,
    image1: `${CDN}/1775074493261-jccylv.jpg`,
    image2: `${CDN}/1775074605323-iygad1.webp`,
    image3: null,
    image4: null,
    basePrice: "45.00",
    duration: "1 día",
    minPersons: 1,
    maxPersons: 5,
    difficulty: "facil",
    isFeatured: 0,
    isActive: 1,
    isPublished: 1,
    isPresentialSale: 1,
    categoryId: catDeportes,
    locationId: locId,
    includes: JSON.stringify(["Tabla de wakeboard", "Fijaciones/herrajes", "Chaleco salvavidas", "Seguro de accidentes"]),
    excludes: JSON.stringify(["Neopreno"]),
    fiscalRegime: "general_21",
    productType: "actividad",
    "pricing_type": "per_person",
    sortOrder: 3,
  },
  {
    slug: "cableski-wakeboard",
    title: "Cableski & Wakeboard",
    shortDescription: "El sistema de cable aéreo continuo te propulsará sobre el agua haciendo wakeboard o esquí acuático. ¡Una experiencia que engancha desde la primera vuelta!",
    description: "El cableski de Náyade te permite practicar wakeboard o esquí acuático impulsado por un sistema de cable aéreo continuo, sin necesidad de lancha motora. No hace falta experiencia previa: el cable hace el trabajo y tú solo tienes que dejarte llevar. Disponible por vueltas o en formato media jornada/jornada completa.",
    coverImageUrl: `${CDN}/1773766863713-7gry6r.jpg`,
    image1: `${CDN}/1773766863713-7gry6r.jpg`,
    image2: `${CDN}/1773766869680-r66be7.png`,
    image3: `${CDN}/1773766880496-2l6cdm.png`,
    image4: `${CDN}/1773766883661-g2yblj.png`,
    basePrice: "30.00",
    duration: null,
    minPersons: 1,
    maxPersons: 100,
    difficulty: "moderado",
    isFeatured: 0,
    isActive: 1,
    isPublished: 1,
    isPresentialSale: 1,
    categoryId: catDeportes,
    locationId: locId,
    includes: JSON.stringify(["Esquís, mono-ski o kneeboard", "Chaleco salvavidas/protector", "Seguro de accidentes"]),
    excludes: JSON.stringify(["Tabla de wakeboard", "Neopreno"]),
    fiscalRegime: "general_21",
    productType: "actividad",
    "pricing_type": "per_person",
    sortOrder: 4,
  },
  {
    slug: "blob-jump",
    title: "Blob Jump",
    shortDescription: "Lánzate desde una plataforma elevada sobre un giant blob inflable y sal despedido al aire. ¡La actividad más adrenalínica del verano!",
    description: "El Blob Jump es la actividad más impactante de Náyade. Te lanzas desde una plataforma elevada sobre un enorme colchón inflable (blob) situado en el agua, que propulsa al compañero que está en el extremo opuesto por los aires antes de caer al embalse. Pura adrenalina para los más valientes. Disponible por saltos individuales o en bonos de 3 y 5 saltos.",
    coverImageUrl: `${CDN}/1773762402377-dymd02.png`,
    image1: `${CDN}/1773762402377-dymd02.png`,
    image2: `${CDN}/1773762413686-d56xu2.png`,
    image3: null,
    image4: null,
    basePrice: "8.00",
    duration: null,
    minPersons: 1,
    maxPersons: 20,
    difficulty: "dificil",
    isFeatured: 1,
    isActive: 1,
    isPublished: 1,
    isPresentialSale: 1,
    categoryId: catAcuaticas,
    locationId: locId,
    includes: JSON.stringify(["Equipo protector (parachoques)", "Seguro de accidentes", "Chaleco salvavidas"]),
    excludes: JSON.stringify(["Casco"]),
    fiscalRegime: "general_21",
    productType: "actividad",
    "pricing_type": "per_person",
    sortOrder: 5,
  },
  {
    slug: "canoas-kayaks",
    title: "Canoas & Kayaks",
    shortDescription: "Explora el embalse en canoa o kayak a tu propio ritmo. Deporte, paisaje y tranquilidad con vistas a la Sierra de Guadarrama.",
    description: "Navega por el embalse de Los Ángeles de San Rafael en canoa o kayak y descubre rincones únicos a tu propio ritmo. Una actividad perfecta para todos los niveles que combina ejercicio suave, contacto con la naturaleza y unas vistas espectaculares de la Sierra de Guadarrama. Disponible en alquiler de 1, 2 o 3 horas, y con Fórmula Familiar para 4 personas.",
    coverImageUrl: `${CDN}/1775063728570-x1kzd8.png`,
    image1: `${CDN}/1775063728570-x1kzd8.png`,
    image2: `${CDN}/1775063736967-y2tlnu.png`,
    image3: `${CDN}/1775063750522-nke2gs.png`,
    image4: `${CDN}/1775063846540-gcz3jp.png`,
    basePrice: "12.00",
    duration: "1 hora",
    minPersons: 2,
    maxPersons: 4,
    difficulty: "facil",
    isFeatured: 1,
    isActive: 1,
    isPublished: 1,
    isPresentialSale: 1,
    categoryId: catAcuaticas,
    locationId: locId,
    includes: JSON.stringify(["Embarcación para 2 pasajeros", "Remos para 2 personas", "Chaleco salvavidas", "Seguro de accidentes"]),
    excludes: JSON.stringify(["Bolsa impermeable"]),
    fiscalRegime: "general_21",
    productType: "actividad",
    "pricing_type": "per_person",
    sortOrder: 6,
  },
  {
    slug: "paddle-surf",
    title: "Paddle Surf",
    shortDescription: "Practica el stand-up paddleboarding en las tranquilas aguas del embalse. Equilibrio, calma y diversión para todos los niveles.",
    description: "El Paddle Surf o Stand-Up Paddleboarding (SUP) es una actividad perfecta para disfrutar del embalse de una manera activa y serena. De pie sobre la tabla, remando con una pala, podrás explorar las orillas del embalse y disfrutar de las vistas. Accesible para principiantes y apto para toda la familia. Disponible en sesiones de 1 hora, 2 horas o Fórmula Familiar.",
    coverImageUrl: `${CDN}/1773774376430-cmec06.png`,
    image1: `${CDN}/1773774376430-cmec06.png`,
    image2: `${CDN}/1773774379647-stk79l.jpg`,
    image3: `${CDN}/1773774382023-qz52s0.jpg`,
    image4: `${CDN}/1773774392088-2ldmdb.jpg`,
    basePrice: "20.00",
    duration: "1 hora",
    minPersons: 1,
    maxPersons: 6,
    difficulty: "facil",
    isFeatured: 1,
    isActive: 1,
    isPublished: 1,
    isPresentialSale: 1,
    categoryId: catAcuaticas,
    locationId: locId,
    includes: JSON.stringify(["Tabla individual", "Remo/pala", "Chaleco salvavidas", "Seguro de accidentes"]),
    excludes: JSON.stringify(["Bolsa estanca impermeable"]),
    fiscalRegime: "general_21",
    productType: "actividad",
    "pricing_type": "per_person",
    sortOrder: 7,
  },
  {
    slug: "banana-ski-donuts-copia-dRMV",
    title: "Donuts Ski",
    shortDescription: "La actividad más divertida para grupos: flota sobre un donut inflable remolcado por una lancha motora a alta velocidad, con giros y salpicones garantizados.",
    description: "El Donuts Ski es, sin duda, la actividad más divertida y apta para todos los públicos de Náyade. Subidos en un flotador circular de goma inflable, serás remolcado por una lancha motora a alta velocidad por las aguas del embalse. Giros inesperados, saltos, curvas pronunciadas y salpicones constantes hacen de esta actividad una experiencia de risa garantizada. Disponible para grupos de 2 a 8 personas.",
    coverImageUrl: `${CDN}/1773863507321-ywvj6b.png`,
    image1: `${CDN}/1773863507321-ywvj6b.png`,
    image2: `${CDN}/1775034710820-bwhf5y.jpg`,
    image3: `${CDN}/1773702422261-h5ajd3.png`,
    image4: `${CDN}/1773702434768-wegear.png`,
    basePrice: "35.00",
    duration: "20 minutos",
    minPersons: 2,
    maxPersons: 8,
    difficulty: "moderado",
    isFeatured: 1,
    isActive: 1,
    isPublished: 1,
    isPresentialSale: 1,
    categoryId: catAcuaticas,
    locationId: locId,
    includes: JSON.stringify(["Equipo y flotador", "Chaleco salvavidas", "Seguro de accidentes"]),
    excludes: JSON.stringify(["Neopreno"]),
    fiscalRegime: "general_21",
    productType: "actividad",
    "pricing_type": "per_person",
    sortOrder: 8,
  },
  {
    slug: "circuito-spa",
    title: "Circuito SPA Hidrotermal",
    shortDescription: "Circuito hidrotérmico completo con piscinas a distintas temperaturas, jacuzzi, sauna finlandesa, baño turco y duchas de contraste.",
    description: "El Circuito SPA Hidrotermal de Náyade te ofrece una experiencia de bienestar completa en un entorno privilegiado. El circuito incluye piscinas a diferentes temperaturas, chorros cervicales y lumbares, sauna finlandesa, baño turco y duchas de contraste. Perfecto para desconectar, recuperarte y mimar tu cuerpo. Disponible con precio especial para clientes del hotel.",
    coverImageUrl: `${CDN}/1773867774581-gde9k3.png`,
    image1: `${CDN}/1773867774581-gde9k3.png`,
    image2: `${CDN}/1773867780249-4it3ac.png`,
    image3: `${CDN}/1773867847070-xh6y0d.png`,
    image4: `${CDN}/1773867967358-gmcgyp.png`,
    basePrice: "18.00",
    duration: null,
    minPersons: 6,
    maxPersons: 20,
    difficulty: "facil",
    isFeatured: 1,
    isActive: 1,
    isPublished: 1,
    isPresentialSale: 1,
    categoryId: catSpa,
    locationId: locId,
    includes: JSON.stringify(["Acceso a todo el circuito hidrotermal", "Piscinas a distintas temperaturas", "Sauna finlandesa", "Baño turco", "Duchas de contraste", "Seguro de accidentes"]),
    excludes: JSON.stringify([]),
    fiscalRegime: "general_21",
    productType: "actividad",
    "pricing_type": "per_person",
    sortOrder: 9,
  },
  {
    slug: "banana-ski-donuts",
    title: "Banana Ski",
    shortDescription: "La actividad más divertida y apta para todos los públicos: sentados en el flotador banana o donut, la lancha os arrastrará a alta velocidad por el embalse.",
    description: "El Banana Ski es la actividad más divertida y popular de Náyade, ideal para grupos y familias. Sentados en un flotador en forma de banana o donut, la lancha motora os remolcará a alta velocidad por las aguas del embalse. Risas, emociones y salpicones están garantizados. Mínimo 4 personas para la tarifa estándar.",
    coverImageUrl: `${CDN}/1773702396972-kd9hrk.png`,
    image1: `${CDN}/1773702396972-kd9hrk.png`,
    image2: `${CDN}/1773702409563-u54xhb.png`,
    image3: `${CDN}/1773702422261-h5ajd3.png`,
    image4: `${CDN}/1773702434768-wegear.png`,
    basePrice: "15.00",
    duration: "20 minutos",
    minPersons: 4,
    maxPersons: 8,
    difficulty: "moderado",
    isFeatured: 1,
    isActive: 1,
    isPublished: 1,
    isPresentialSale: 1,
    categoryId: catAcuaticas,
    locationId: locId,
    includes: JSON.stringify(["Seguro de accidentes"]),
    excludes: JSON.stringify([]),
    fiscalRegime: "general_21",
    productType: "actividad",
    "pricing_type": "per_person",
    sortOrder: 10,
  },
  {
    slug: "hidropedales",
    title: "Hidrobicis",
    shortDescription: "Pedalea sobre el agua y explora el embalse a tu ritmo. Una actividad tranquila y relajante perfecta para toda la familia.",
    description: "Las hidrobicis (o hidropedales) son la opción perfecta para disfrutar del embalse de forma relajada y sin esfuerzo. Pedaleando sobre el agua podrás explorar los rincones más tranquilos del embalse, disfrutar de las vistas y descansar. Ideal para familias con niños y para quienes buscan una actividad sin adrenalina. Disponible en sesiones de 1 hora, 2 horas o Fórmula Familiar.",
    coverImageUrl: `${CDN}/1773777174336-io6lvw.jpg`,
    image1: `${CDN}/1773777174336-io6lvw.jpg`,
    image2: `${CDN}/1773777177100-p1hzuw.jpg`,
    image3: `${CDN}/1773777198906-716boe.png`,
    image4: null,
    basePrice: "20.00",
    duration: "1 hora",
    minPersons: 2,
    maxPersons: 4,
    difficulty: "moderado",
    isFeatured: 1,
    isActive: 1,
    isPublished: 1,
    isPresentialSale: 1,
    categoryId: catAcuaticas,
    locationId: locId,
    includes: JSON.stringify(["Hidropedal", "Chaleco salvavidas", "Seguro de accidentes"]),
    excludes: JSON.stringify(["Neopreno"]),
    fiscalRegime: "general_21",
    productType: "actividad",
    "pricing_type": "per_person",
    sortOrder: 11,
  },
  {
    slug: "aventura-hinchable",
    title: "Aventura Hinchable Acuática",
    shortDescription: "Parque inflable flotante en el lago con toboganes, trampolines y circuitos de obstáculos. ¡Diversión garantizada para todas las edades!",
    description: "La Aventura Hinchable Acuática es el parque de atracciones flotante de Náyade: un enorme recorrido inflable situado en el embalse con toboganes, trampolines, muros de escalada y circuitos de obstáculos para superar. Diversión y risas garantizadas para toda la familia. Especialmente indicado para niños, pero igualmente divertido para adultos. Disponible en sesiones de 30 y 60 minutos.",
    coverImageUrl: `${CDN}/1773778862239-e30o1s.png`,
    image1: `${CDN}/1773778862239-e30o1s.png`,
    image2: `${CDN}/1773778867350-w70k1r.png`,
    image3: `${CDN}/1773779017020-g7xxyf.png`,
    image4: null,
    basePrice: "8.00",
    duration: "1 hora",
    minPersons: 1,
    maxPersons: 30,
    difficulty: "facil",
    isFeatured: 1,
    isActive: 1,
    isPublished: 1,
    isPresentialSale: 1,
    categoryId: catAcuaticas,
    locationId: locId,
    includes: JSON.stringify(["Seguro de accidentes"]),
    excludes: JSON.stringify([]),
    fiscalRegime: "general_21",
    productType: "actividad",
    "pricing_type": "per_person",
    sortOrder: 12,
  },
];

// ── Insertar todas las experiencias ─────────────────────────────────────────
for (const exp of experiences) {
  await insertExp(exp);
  console.log(`✅ ${exp.title} (${exp.slug})`);
}

// ── Verificación final ───────────────────────────────────────────────────────
const [rows] = await conn.execute(
  `SELECT id, slug, title, basePrice, isActive, isPublished FROM experiences ORDER BY sortOrder`
);
console.log("\n📋 Experiencias en BD:");
rows.forEach(r => console.log(`  [${r.id}] ${r.title} — ${r.basePrice}€`));

await conn.end();
console.log("\n🎉 Seed completado");
